# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches: [ main ]

env: 
  deploy-folder: /home/github-action/deployments/vaccine-slot-bot
  config-folder: /home/github-action/configs/vaccine-slot-bot


jobs:
  build_and_deploy:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
    - run: npm i --only=production
    - name: Copy Artifacts
    - run: cp -r ./src ${{ env.deploy-folder }}
    - run: cp -r ./package.json ${{ env.deploy-folder }}
    - run: cp -r ./node_modules ${{ env.deploy-folder }}
    - name: Copy Configuration
    - run: cp -r ${{ env.config-folder }}/config.json ${{ env.deploy-folder }}/config.json
  

