# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i --only=production
    - run: cp -r ./src ~/deployments/vaccine-bot-slot
    - run: cp -r ./package.json ~/deployments/vaccine-bot-slot
    - run: cp -r ./node_modules ~/deployments/vaccine-bot-slot
    - run: cp -r ~/configs/vaccine-bot-slot/config.json ~/deployments/vaccine-bot-slot/config.json
